# Generated by Django 3.2 on 2021-05-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmodel',
            name='patientpic',
            field=models.ImageField(blank='True', null='True', upload_to=''),
            preserve_default='True',
        ),
    ]
