# Generated by Django 3.2 on 2021-05-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_empmodel_patientpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmodel',
            name='adhar',
            field=models.BooleanField(default=True),
        ),
    ]
