# Generated by Django 3.2 on 2021-05-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_empmodel_adhar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empmodel',
            old_name='adhar',
            new_name='history',
        ),
    ]
