# Generated by Django 3.2 on 2021-05-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_rename_adhar_empmodel_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmodel',
            name='history',
            field=models.BooleanField(),
        ),
    ]
