# Generated by Django 3.2 on 2021-05-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_empmodel_site'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empmodel',
            table='capstone',
        ),
    ]
