# Generated by Django 3.2 on 2021-05-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_alter_empmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empmodel',
            table='prescription',
        ),
    ]
